"""added initiator id column

Revision ID: 61c208d1bf17
Revises: 9aa53122b2a3
Create Date: 2025-09-06 13:50:14.092481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c208d1bf17'
down_revision: Union[str, Sequence[str], None] = '9aa53122b2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_requests', sa.Column('initiator_id', sa.String(), nullable=True))
    op.alter_column('match_requests', 'requester_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'match_requests', 'profiles', ['initiator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match_requests', type_='foreignkey')
    op.alter_column('match_requests', 'requester_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('match_requests', 'initiator_id')
    # ### end Alembic commands ###
