"""added report field for posts/profiles 

Revision ID: 628cd4d6a846
Revises: 9be7c5962508
Create Date: 2025-09-11 17:54:52.197150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '628cd4d6a846'
down_revision: Union[str, Sequence[str], None] = '9be7c5962508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('reports', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('profiles', sa.Column('reports', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('requests', sa.Column('reports', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'reports')
    op.drop_column('profiles', 'reports')
    op.drop_column('offers', 'reports')
    # ### end Alembic commands ###
