"""changed phone_hashed to phone

Revision ID: 9aa53122b2a3
Revises: a4bc0c3d5668
Create Date: 2025-09-06 01:22:50.681004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aa53122b2a3'
down_revision: Union[str, Sequence[str], None] = 'a4bc0c3d5668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('phone', sa.String(length=64), nullable=True))
    op.drop_column('profiles', 'phone_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('phone_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'phone')
    # ### end Alembic commands ###
