"""added subcategory field in request/offers

Revision ID: 9be7c5962508
Revises: 61c208d1bf17
Create Date: 2025-09-07 01:15:49.895640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be7c5962508'
down_revision: Union[str, Sequence[str], None] = '61c208d1bf17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('subcategory', sa.String(length=50), nullable=True))
    op.add_column('requests', sa.Column('subcategory', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'subcategory')
    op.drop_column('offers', 'subcategory')
    # ### end Alembic commands ###
