"""add contact fields

Revision ID: a40cc7c9815c
Revises: c812dc53999d
Create Date: 2025-09-04 21:50:30.557875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a40cc7c9815c'
down_revision: Union[str, Sequence[str], None] = 'c812dc53999d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_requests', sa.Column('requester_contact_mode', sa.String(length=20), nullable=True))
    op.add_column('match_requests', sa.Column('requester_contact_value', sa.String(length=100), nullable=True))
    op.add_column('match_requests', sa.Column('offerer_contact_mode', sa.String(length=20), nullable=True))
    op.add_column('match_requests', sa.Column('offerer_contact_value', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_requests', 'offerer_contact_value')
    op.drop_column('match_requests', 'offerer_contact_mode')
    op.drop_column('match_requests', 'requester_contact_value')
    op.drop_column('match_requests', 'requester_contact_mode')
    # ### end Alembic commands ###
