"""add email to profiles

Revision ID: a4bc0c3d5668
Revises: a40cc7c9815c
Create Date: 2025-09-04 23:15:06.157092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4bc0c3d5668'
down_revision: Union[str, Sequence[str], None] = 'a40cc7c9815c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'profiles', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'email')
    # ### end Alembic commands ###
