"""changed field name

Revision ID: c812dc53999d
Revises: e32c506f33be
Create Date: 2025-09-02 12:57:23.480318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c812dc53999d'
down_revision: Union[str, Sequence[str], None] = 'e32c506f33be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('image_file_name', sa.Text(), nullable=True))
    op.drop_column('offers', 'image_url')
    op.add_column('requests', sa.Column('image_file_name', sa.Text(), nullable=True))
    op.drop_column('requests', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('requests', 'image_file_name')
    op.add_column('offers', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('offers', 'image_file_name')
    # ### end Alembic commands ###
