"""add image_url to requests

Revision ID: e32c506f33be
Revises: 5df74c150c93
Create Date: 2025-08-30 02:57:44.328759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32c506f33be'
down_revision: Union[str, Sequence[str], None] = '5df74c150c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('requests', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'image_url')
    op.drop_column('offers', 'image_url')
    # ### end Alembic commands ###
